{% set name = "python-docker" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: bc803ab299cdab6f7ed541091fc19f5523ae3284c708f4b554cece8a6739cae4

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - pydantic
    - requests

test:
  imports:
    - python_docker

about:
  home: https://github.com/costrouc/python-docker
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Build docker images and interact with registries without docker
  description: |
    A pure python implementation to build docker images without docker
    and provide a python api for interacting with docker registries
  dev_url: https://github.com/costrouc/python-docker

extra:
  recipe-maintainers:
    - costrouc
